name: Reviews

permissions:
  pull-requests: write

on:
  workflow_run:
    workflows:
      - Static-Analysis
      - Tests
    types:
      - completed

jobs:
  approve:
    if: github.event.pull_request.user.login == github.repository_owner && ! github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/auto-approve-action@v3
